let
    Fonte = Csv.Document(File.Contents("\\10.0.20.65\DirJudiciaria\Gabinete\Comum\Cleyton\2024\Fevereiro\Câmaras\lista Câmaras dia 27 a 05 Fev a Mar.txt"),[Delimiter="#", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Column1", Int64.Type}, {"Column2", type text}, {"Column3", type text}, {"Column4", type datetime}, {"Column5", type text}}),
    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Tipo Alterado",{{"Column5", Text.Proper, type text}}),
    #"Texto Extraído Antes do Delimitador" = Table.TransformColumns(#"Colocar Cada Palavra Em Maiúscula", {{"Column5", each Text.BeforeDelimiter(_, "-"), type text}}),
    #"Remover Espaco Final Nome" = Table.TransformColumns(#"Texto Extraído Antes do Delimitador",{{"Column5", each if Text.EndsWith(_, "a") then Text.Start(_, Text.Length(_) - 1) else _}}),
    #"Remover Nome Desembargador" = Table.AddColumn(#"Remover Espaco Final Nome", "Unidade Tratada", each if Text.StartsWith([Column2], "Seção Criminal") then "Seção Criminal" else if Text.StartsWith([Column2], "1ª Câmara Criminal") then "1ª Câmara Criminal" else if Text.StartsWith([Column2], "2ª Câmara Criminal") then "2ª Câmara Criminal" else if Text.StartsWith([Column2], "3ª Câmara Criminal") then "3ª Câmara Criminal" else if Text.StartsWith([Column2], "4ª Câmara Criminal") then "4ª Câmara Criminal" else if Text.StartsWith([Column2], "Gabinete de Juiz Auxiliar") then "Gabinete de Juiz Auxiliar" else if Text.StartsWith([Column2], "Gabinete de JUIZ AUXILIAR") then "Gabinete de Juiz Auxiliar" else if Text.StartsWith([Column2], "1ª Câmara Cível") then "1ª Câmara Cível" else if Text.StartsWith([Column2], "2ª Câmara Cível") then "2ª Câmara Cível" else if Text.StartsWith([Column2], "3ª Câmara Cível") then "3ª Câmara Cível" else if Text.StartsWith([Column2], "4ª Câmara Cível") then "4ª Câmara Cível" else if Text.StartsWith([Column2], "4ª câmara cível") then "4ª Câmara Cível" else if Text.StartsWith([Column2], "5ª Câmara Cível") then "5ª Câmara Cível" else if Text.StartsWith([Column2], "6ª Câmara Cível") then "6ª Câmara Cível" else if Text.StartsWith([Column2], "7ª Câmara Cível") then "7ª Câmara Cível" else if Text.StartsWith([Column2], "8ª Câmara Cível") then "8ª Câmara Cível" else if Text.StartsWith([Column2], "9ª Câmara Cível") then "9ª Câmara Cível" else if Text.StartsWith([Column2], "10ª Câmara Cível") then "10ª Câmara Cível" else if Text.StartsWith([Column2], "11ª Câmara Cível") then "11ª Câmara Cível" else if Text.StartsWith([Column2], "1ª Seção Cível") then "1ª Seção Cível" else if Text.StartsWith([Column2], "2ª Seção Cível") then "2ª Seção Cível" else if Text.StartsWith([Column2], "3ª Seção Cível") then "3ª Seção Cível" else if Text.StartsWith([Column2], "3ª Câmara Civel") then "3ª Câmara Civel" else if Text.StartsWith([Column2], "Gab. de JUIZ AUXILIAR") then "Gabinete de Juiz Auxiliar" else if Text.StartsWith([Column2], "Órgão Especial") then "Órgão Especial" else if Text.StartsWith([Column2], "Conselho Sup da Magistratura") then "Conselho Sup da Magistratura" else [Column2]),
    #"Colunas Reordenadas" = Table.ReorderColumns(#"Remover Nome Desembargador",{"Column1", "Unidade Tratada", "Column3", "Column4", "Column5", "Column2"}),
    #"Consultas Mescladas" = Table.NestedJoin(#"Colunas Reordenadas", {"Unidade Tratada"}, Tab_Unidade2, {"UNIDADE"}, "Tab_Unidade2", JoinKind.LeftOuter),
    #"Tab_Unidade2 Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "Tab_Unidade2", {"GRAU", "TIPO"}, {"GRAU", "TIPO"}),
    #"Colunas Reordenadas1" = Table.ReorderColumns(#"Tab_Unidade2 Expandido",{"Column1", "Unidade Tratada", "Column3", "Column4", "Column5", "GRAU", "Column2", "TIPO"}),
    #"Nome do Mês Inserido" = Table.AddColumn(#"Colunas Reordenadas1", "Nome do Mês", each Date.MonthName([Column4]), type text),
    #"Colocar Cada Palavra Em Maiúscula1" = Table.TransformColumns(#"Nome do Mês Inserido",{{"Nome do Mês", Text.Proper, type text}}),
    #"Colunas Reordenadas2" = Table.ReorderColumns(#"Colocar Cada Palavra Em Maiúscula1",{"Column1", "Unidade Tratada", "Column3", "Column4", "Column5", "Nome do Mês", "GRAU", "TIPO", "Column2"})
in
    #"Colunas Reordenadas2"
