let
    Fonte = Csv.Document(File.Contents("\\10.0.20.65\DirJudiciaria\Gabinete\Comum\Cleyton\2024\03 Março\Câmaras\lista Câmaras 25 a 31 março.txt"),[Delimiter="#", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Column1", Int64.Type}, {"Column2", type text}, {"Column3", type text}, {"Column4", type datetime}, {"Column5", type text}}),
    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Column2", "Comarca"}, {"Column3", "Movimentação"}, {"Column4", "Data"}, {"Column5", "Nome"}}),
    #"Data Extraída" = Table.TransformColumns(#"Colunas Renomeadas",{{"Data", DateTime.Date, type date}}),
    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(#"Data Extraída",{{"Nome", Text.Proper, type text}}),
    #"Texto Extraído Antes do Delimitador" = Table.TransformColumns(#"Colocar Cada Palavra Em Maiúscula", {{"Nome", each Text.BeforeDelimiter(_, "-"), type text}}),
    #"Texto Limpo" = Table.TransformColumns(#"Texto Extraído Antes do Delimitador",{{"Nome", each if Text.EndsWith(_, " ") then Text.Start(_, Text.Length(_) - 1) else _}}),
    #"Linhas Agrupadas" = Table.Group(#"Texto Limpo", {"Comarca", "Movimentação", "Data", "Nome"}, {{"Contagem", each Table.RowCount(_), Int64.Type}}),
    #"Colunas Renomeadas1" = Table.RenameColumns(#"Linhas Agrupadas",{{"Comarca", "Column2"}}),
    #"Remover Nome Desembargador" = Table.AddColumn(#"Colunas Renomeadas1", "Unidade Tratada", each if Text.StartsWith([Column2], "Seção Criminal") then "Seção Criminal" else if Text.StartsWith([Column2], "1ª Câmara Criminal") then "1ª Câmara Criminal" else if Text.StartsWith([Column2], "2ª Câmara Criminal") then "2ª Câmara Criminal" else if Text.StartsWith([Column2], "3ª Câmara Criminal") then "3ª Câmara Criminal" else if Text.StartsWith([Column2], "4ª Câmara Criminal") then "4ª Câmara Criminal" else if Text.StartsWith([Column2], "Gabinete de Juiz Auxiliar") then "Gabinete de Juiz Auxiliar" else if Text.StartsWith([Column2], "Gabinete de JUIZ AUXILIAR") then "Gabinete de Juiz Auxiliar" else if Text.StartsWith([Column2], "1ª Câmara Cível") then "1ª Câmara Cível" else if Text.StartsWith([Column2], "2ª Câmara Cível") then "2ª Câmara Cível" else if Text.StartsWith([Column2], "3ª Câmara Cível") then "3ª Câmara Cível" else if Text.StartsWith([Column2], "4ª Câmara Cível") then "4ª Câmara Cível" else if Text.StartsWith([Column2], "4ª câmara cível") then "4ª Câmara Cível" else if Text.StartsWith([Column2], "5ª Câmara Cível") then "5ª Câmara Cível" else if Text.StartsWith([Column2], "6ª Câmara Cível") then "6ª Câmara Cível" else if Text.StartsWith([Column2], "7ª Câmara Cível") then "7ª Câmara Cível" else if Text.StartsWith([Column2], "8ª Câmara Cível") then "8ª Câmara Cível" else if Text.StartsWith([Column2], "9ª Câmara Cível") then "9ª Câmara Cível" else if Text.StartsWith([Column2], "10ª Câmara Cível") then "10ª Câmara Cível" else if Text.StartsWith([Column2], "11ª Câmara Cível") then "11ª Câmara Cível" else if Text.StartsWith([Column2], "1ª Seção Cível") then "1ª Seção Cível" else if Text.StartsWith([Column2], "2ª Seção Cível") then "2ª Seção Cível" else if Text.StartsWith([Column2], "3ª Seção Cível") then "3ª Seção Cível" else if Text.StartsWith([Column2], "3ª Câmara Civel") then "3ª Câmara Civel" else if Text.StartsWith([Column2], "Gab. de JUIZ AUXILIAR") then "Gabinete de Juiz Auxiliar" else if Text.StartsWith([Column2], "Órgão Especial") then "Órgão Especial" else if Text.StartsWith([Column2], "Conselho Sup da Magistratura") then "Conselho Sup da Magistratura" else [Column2]),
    #"Linhas Filtradas" = Table.SelectRows(#"Remover Nome Desembargador", each true),
    #"Colunas Removidas" = Table.RemoveColumns(#"Linhas Filtradas",{"Column2"}),
    #"Personalização Adicionada" = Table.AddColumn(#"Colunas Removidas", "Tipo", each "Processo"),
    #"Colunas Reordenadas" = Table.ReorderColumns(#"Personalização Adicionada",{"Unidade Tratada", "Movimentação", "Data", "Nome", "Tipo", "Contagem"}),
    #"Consultas Mescladas" = Table.NestedJoin(#"Colunas Reordenadas", {"Unidade Tratada"}, Tab_Unidade2, {"UNIDADE"}, "Tab_Unidade2", JoinKind.LeftOuter),
    #"Tab_Unidade2 Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "Tab_Unidade2", {"TIPO"}, {"Tab_Unidade2.TIPO"}),
    #"Nome do Mês Inserido" = Table.AddColumn(#"Tab_Unidade2 Expandido", "Nome do Mês", each Date.MonthName([Data]), type text),
    #"Colocar Cada Palavra Em Maiúscula1" = Table.TransformColumns(#"Nome do Mês Inserido",{{"Nome do Mês", Text.Proper, type text}}),
    #"Colunas Reordenadas1" = Table.ReorderColumns(#"Colocar Cada Palavra Em Maiúscula1",{"Unidade Tratada", "Movimentação", "Data", "Nome", "Nome do Mês", "Tipo", "Contagem", "Tab_Unidade2.TIPO"}),
    #"Linhas Filtradas1" = Table.SelectRows(#"Colunas Reordenadas1", each ([Tab_Unidade2.TIPO] <> "NAC" and [Tab_Unidade2.TIPO] <> "OAB"))
in
    #"Linhas Filtradas1"
